apiVersion: v1
kind: ReplicationController  
metadata:
  name: vertex-rc
spec:
   replicas: 3
   selector:
     app: myvertexapp
   template: 
     metadata:
       name: complexpod
       labels:
         app: myvertexapp
     spec:
       containers:
         - name: mynginx-container
           image: snehasirsilla20/myphp17nov:1
           ports:
            - containerPort: 8080   

