apiVersion: v1
kind: ReplicationController  
metadata:
  name: myonlineapp-rc
spec:
   replicas: 2
   selector:
     app: myvertexpod
     version: 2.6.2
   template: 
     metadata:
       labels:
         app: myvertexpod
         version: 2.6.2
     spec:
       containers:
         - name: myonlineapp-container
           image: nginx
           ports:
            - containerPort: 80    

