apiVersion: v1
kind: ReplicationController  
metadata:
  name: vertex-rc
spec:
   replicas: 3
   selector:
     app: myvertexapp
     version: 2.6.1
   template: 
     metadata:
       name: complexpod
       labels:
         app: myvertexapp
         version: 2.6.1
     spec:
       containers:
         - name: mynginx-container
           image: snehasirsilla20/myjavaimage3dec22:1
           ports:
            - containerPort: 8080   

